BACKGROUND_COLOR = '#262626'

TITLE = ('YMCA Account Creation Program')
SCREEN_SIZE_STRING = ('900x600')
SCREEN_SIZE = (900, 600)
SCREEN_WIDTH = SCREEN_SIZE[0]
SCREEN_HEIGHT = SCREEN_SIZE[1]

SCREEN_CENTER_WIDTH = SCREEN_SIZE[0]//2
SCREEN_CENTER_HEIGHT = SCREEN_SIZE[1]//2
SCREEN_CENTER = (SCREEN_CENTER_WIDTH, SCREEN_CENTER_HEIGHT)

if __name__ == '__main__':
    exec(open("CodeRework/main.py").read())